version: 1.0.{build}

environment:
  PYTHON: "C:\\Python39"
  PYTHON_VERSION: "3.9.0"
  PYTHON_ARCH: "32"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pyinstaller

build_script:
  - pyinstaller --onefile VideoAvgColorLines.py

artifacts:
  - path: dist\VideoAvgColorLines.exe
    name: executable

test: off

deploy: off 